name: weather
description: A Flutter weather app for portfolio.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^8.0.1
  google_fonts: ^2.1.0
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.1
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/weather_icons/day/
    - assets/weather_icons/night/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf

flutter_intl:
  enabled: true
